name: update-parent
on:
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: shunueda/shu-nu
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - run: |
          git submodule update --recursive --remote
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add --all
          git commit -m "chore(submodule): update" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
