name: update-parent
on:
  push:
    branches:
      - main
      - preview
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          repository: shunueda/shu-nu
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          submodules: true
      - run: |
          git submodule update --recursive --remote
          git config user.email "actions@github.com"
          git config user.name "actions-user"
          git add --all
          git commit -m "chore(submodule): update"
          git push origin main
